version: "3.1"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    restart: always
    networks:
      - awesome
  front:
    build:
      context: ./front
    depends_on:
      - backend
    environment:
      FRONT_PORT: 3000
    ports:
      - "4000:3000"
    restart: always
    networks:
      - awesome
networks:
    awesome:
        driver: bridge
